version: '3.1'

services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
        - PORT=3000
    volumes:
      - ./src:/home/node/app/src
      - ./data:/home/node/app/data
    ports:
      - "3000:3000"
    environment:
      - "NODE_ENV=development"
    command: ["nodemon", "bin/www"]
